### PR TITLE
Return nil rather than raising if a JPEG has no XMP metadata

### PR DESCRIPTION
**Pull request by dschweisguth**
In 0.2, `XMP.parse` returned nil for a JPEG with no XMP metadata. In 1.0 it raises "NoMethodError: undefined method `[]' for nil:NilClass". My app that uses XMP has encountered such JPEGs in the wild, so I think this is a regression that's worth fixing.

This PR restores the 0.2 behavior. In doing so, it removes the behavior, new in 1.0, that `XMP.parse` raises "cannot handle" if none of its handlers return a non-nil result. This seems to me like the simplest way to fix the regression, as there are probably not yet any clients that rely on the new exception.

It should also be possible to preserve the exception for input that XMP doesn't recognize at all, but that would be a bigger change (I'd want to add simplecov to the test suite and add any tests needed to more or less fully cover the existing code before changing it), and no tests require the exception, so I took the easy way out. I'd be happy to do something different if other think it would be helpful.

### CODE REVIEW

**Comment by dschweisguth** [comment]
@wpiekutowski let me know if tagging you is unnecessary or unwanted :)

**Comment by wpiekutowski** [comment]
Thanks for reporting this. I agree that this is a bug. There should be a test case covering this to avoid such regressions in the future.

It would be great if we could have a better test coverage overall or at least have an understanding how much we're missing. If you are up to it, PR is welcome!

I'm leaning towards returning an "empty" `XMP::Document` when there's no XMP metadata. It could make sense to add an  `empty?` method as well. What do you think?

**Comment by dschweisguth** [comment]
I agree, an empty `XMP::Document` would be a good return value when there's no XMP metadata. That wouldn't really be a breaking change from the 0.2 behavior (returning nil), since clients that use the gem with arbitrary images already had to handle images with XMP metadata that doesn't have the elements they expect.

Yes, `#empty?` sounds reasonable.

I think it would be best to continue raising the exception when a client tries to parse unsupported data. Returning empty metadata for something that shouldn't have metadata at all seems wrong to me. What do you think there?

Meanwhile, I'll do a PR for coverage.

**Comment by wpiekutowski** [comment]
It would be a breaking change though, as `nil` is very different than an
empty `Document` and Ruby threats these differently when it comes to
truthiness. But that's ok, I'll release 2.0.0.

+1 for raising the exception when parsing unsupported image types, etc.

**Comment by dschweisguth** [comment]
https://github.com/amberbit/xmp/pull/12 does some preliminary work. I'll change what is returned when there's no XMP metadata in a separate PR.

**Pull request closed without merging**
